mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.shushu.blogsystem.mybatis.entity
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
    port: 8088
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/shu_shu?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123456
    servlet:
        multipart:
            location: E:\Jonah_Blog\uploadPath